@Restaurants.Api_HostAddress = http://localhost:5041

GET {{Restaurants.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@restaurantId=1
GET {{Restaurants.Api_HostAddress}}/api/restaurants/{id:int}?restaurantId={{restaurantId}}

###
